import { User, Dataset } from './types';
export const MOCK_USERS: User[] = [
  { id: 'user-1', name: 'Alice (Admin)', email: 'alice@example.com', role: 'Admin' },
  { id: 'user-2', name: 'Bob (Data Owner)', email: 'bob@example.com', role: 'Data Owner' },
  { id: 'user-3', name: 'Charlie (Contributor)', email: 'charlie@example.com', role: 'Contributor' },
  { id: 'user-4', name: 'Diana (Viewer)', email: 'diana@example.com', role: 'Viewer' },
];
export const MOCK_DATASETS: Dataset[] = [
  {
    id: 'ds-001',
    title: 'Quarterly Financial Report',
    description: 'A comprehensive report detailing the financial performance of the company for the last quarter. Includes revenue, profit margins, and expense breakdowns.',
    ownerId: 'user-2',
    contributorIds: ['user-3'],
    visibility: 'Private',
    metadata: {
      keywords: ['finance', 'revenue', 'q3', 'report'],
      categories: ['Financial', 'Internal'],
      publisher: 'Finance Department',
      contact_email: 'finance@example.com',
      coverage_geographic: 'Global',
      coverage_time: { start_date: '2023-07-01T00:00:00Z', end_date: '2023-09-30T23:59:59Z' },
      methodology: 'Standard accounting practices.',
      data_dictionary: 'https://example.com/dict/financial-report',
      license: 'Internal Use Only',
      update_frequency: 'quarterly',
      version: '1.2.0',
      data_quality_notes: 'Data audited by internal team.'
    },
    files: [{ name: 'Q3_Financials.csv', url: '/files/Q3_Financials.csv', type: 'CSV' }],
    createdAt: new Date('2023-10-15T10:00:00Z').toISOString(),
    updatedAt: new Date('2023-10-16T11:30:00Z').toISOString(),
  },
  {
    id: 'ds-002',
    title: 'Customer Demographics Survey',
    description: 'Anonymized survey data from our Q2 customer satisfaction and demographics survey. Useful for market segmentation and product development.',
    ownerId: 'user-2',
    contributorIds: [],
    visibility: 'Public',
    metadata: {
      keywords: ['customers', 'survey', 'demographics', 'market research'],
      categories: ['Marketing', 'Customer Data'],
      publisher: 'Marketing Department',
      contact_email: 'marketing@example.com',
      coverage_geographic: 'North America',
      coverage_time: { start_date: '2023-04-01T00:00:00Z', end_date: '2023-06-30T23:59:59Z' },
      methodology: 'Online survey distributed via email newsletter.',
      data_dictionary: 'https://example.com/dict/customer-survey',
      license: 'CC BY 4.0',
      update_frequency: 'one-time',
      version: '1.0.0',
    },
    files: [{ name: 'Customer_Demographics.csv', url: '/files/Customer_Demographics.csv', type: 'CSV' }],
    createdAt: new Date('2023-07-20T14:00:00Z').toISOString(),
    updatedAt: new Date('2023-07-20T14:00:00Z').toISOString(),
  },
  {
    id: 'ds-003',
    title: 'Website Traffic Analytics',
    description: 'Daily website traffic data, including page views, user sessions, bounce rate, and referral sources. Sourced from our analytics platform.',
    ownerId: 'user-2',
    contributorIds: ['user-3'],
    visibility: 'Public',
    metadata: {
      keywords: ['analytics', 'website', 'traffic', 'sessions'],
      categories: ['Marketing', 'Web Analytics'],
      publisher: 'Marketing Department',
      contact_email: 'marketing@example.com',
      coverage_geographic: 'Global',
      coverage_time: { start_date: '2023-01-01T00:00:00Z', end_date: new Date().toISOString() },
      methodology: 'Data collected via Google Analytics tracking script.',
      data_dictionary: 'https://example.com/dict/web-analytics',
      license: 'CC BY-NC-SA 4.0',
      update_frequency: 'daily',
      version: '3.1.0',
    },
    files: [{ name: 'web_traffic_daily.json', url: '/files/web_traffic_daily.json', type: 'JSON' }],
    createdAt: new Date('2023-01-02T08:00:00Z').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ds-004',
    title: 'Product Inventory Levels',
    description: 'Real-time inventory levels for all products across all warehouses. This dataset is critical for supply chain management and sales forecasting.',
    ownerId: 'user-2',
    contributorIds: [],
    visibility: 'Private',
    metadata: {
      keywords: ['inventory', 'supply chain', 'warehouse', 'stock'],
      categories: ['Operations', 'Logistics'],
      publisher: 'Operations Team',
      contact_email: 'ops@example.com',
      coverage_geographic: 'USA, Europe',
      coverage_time: { start_date: '2022-01-01T00:00:00Z', end_date: new Date().toISOString() },
      methodology: 'Direct feed from Warehouse Management System (WMS).',
      data_dictionary: 'https://example.com/dict/inventory',
      license: 'Internal Use Only',
      update_frequency: 'daily',
      version: '2.5.0',
      data_quality_notes: 'Occasional latency of up to 15 minutes from WMS.',
    },
    files: [{ name: 'inventory_levels.xlsx', url: '/files/inventory_levels.xlsx', type: 'XLSX' }],
    createdAt: new Date('2022-01-01T00:00:00Z').toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
  },
];